"use strict";
const $=id=>document.getElementById(id);let key="",offset=0,total=0,tab="overview";
function notice(text,error=false){$("notice").textContent=text;$("notice").className=error?"error":"";}
async function api(path,method="GET",data){if(!key)throw Error("Enter the admin API key first");const r=await fetch("/api/admin"+path,{method,headers:{"X-Api-Key":key,"Content-Type":"application/json"},body:data===undefined?undefined:JSON.stringify(data),cache:"no-store",redirect:"error"});const text=await r.text();let json;try{json=text?JSON.parse(text):null;}catch{throw Error("Unexpected server response ("+r.status+")");}if(!r.ok)throw Error(json?.Message||json?.message||"Request failed: "+r.status);return json;}
function action(id,fn){$(id).addEventListener("click",async e=>{e.preventDefault();const b=e.currentTarget;b.disabled=true;try{await fn();}catch(err){notice(err.message,true);}finally{b.disabled=false;}});}
function table(target,headers,rows,open){const t=document.createElement("table"),head=t.createTHead().insertRow();for(const h of headers){const th=document.createElement("th");th.textContent=h;head.append(th);}for(const row of rows){const tr=t.insertRow();row.values.forEach(v=>{const cell=tr.insertCell();cell.textContent=v??"";});if(open){const cell=tr.insertCell(),b=document.createElement("button");b.textContent="Open";b.onclick=()=>Promise.resolve(open(row.data)).catch(e=>notice(e.message,true));cell.append(b);}}$(target).replaceChildren(t);}
async function load(){if(tab==="overview"){const s=await api("/stats");$("stats").replaceChildren(...Object.entries(s).map(([name,value])=>{const c=document.createElement("div");c.className="card";const strong=document.createElement("strong");strong.textContent=value;c.append(strong,document.createTextNode(name.replaceAll("_"," ")));return c;}));}if(tab==="items"){const s=await api("/items?limit=25&offset="+offset+"&search="+encodeURIComponent($("term").value));total=s.total;table("itemlist",["Title","Type","Library",""],s.items.map(i=>({values:[i.Name,i.Type,i.LibraryID],data:i})),editItem);$("page").textContent=` ${offset+1}-${Math.min(offset+25,total)} / ${total} `;$("prev").disabled=offset===0;$("next").disabled=offset+25>=total;}if(tab==="libraries"){const s=await api("/libraries");table("liblist",["Name","Type","ID"],s.map(i=>({values:[i.Name,i.Type,i.ID]})));}if(tab==="users"){const s=await api("/users");table("userlist",["Name","Admin","ID",""],s.map(u=>({values:[u.name,u.is_admin,u.id],data:u})),u=>{$("userid").value=u.id;$("policy").value=typeof u.policy==="string"?u.policy:JSON.stringify(u.policy||{},null,2);});}}
async function editItem(i){$("itemid").value=i.ID;$("itemname").value=i.Name;$("itemlib").value=i.LibraryID;$("itemtype").value=i.Type;$("itemoverview").value=i.Overview||"";await sources();}
async function sources(){const id=$("itemid").value;if(!id)return;const s=await api("/items/"+encodeURIComponent(id)+"/sources");table("sources",["Name","Container",""],s.map(x=>({values:[x.Name,x.Container],data:x})),async x=>{if(confirm("Delete playback source "+x.Name+"?")){await api("/items/"+encodeURIComponent(id)+"/sources/"+encodeURIComponent(x.ID),"DELETE");await sources();}});}
$("login").onsubmit=async e=>{e.preventDefault();key=$("key").value;$("key").value="";try{await load();notice("Connected. Admin credentials are held only in this tab's memory.");}catch(err){key="";notice(err.message,true);}};
for(const b of document.querySelectorAll("[data-tab]"))b.onclick=async()=>{tab=b.dataset.tab;for(const s of document.querySelectorAll("main>section"))s.hidden=s.id!==tab;try{await load();}catch(e){notice(e.message,true);}};
action("disconnect",()=>{key="";location.reload();});action("refresh",load);action("flush",async()=>{await api("/progress/flush","POST");notice("Playback progress persisted.");});
$("search").onsubmit=async e=>{e.preventDefault();offset=0;try{await load();}catch(e){notice(e.message,true);}};
action("prev",async()=>{offset=Math.max(0,offset-25);await load();});action("next",async()=>{offset+=25;await load();});
action("newitem",()=>{["itemid","itemname","itemlib","itemoverview"].forEach(id=>$(id).value="");$("sources").replaceChildren();});
action("saveitem",async()=>{const id=$("itemid").value;const data=id?{name:$("itemname").value,overview:$("itemoverview").value}:{Name:$("itemname").value,LibraryId:$("itemlib").value,Type:$("itemtype").value,Overview:$("itemoverview").value};await api("/items"+(id?"/"+encodeURIComponent(id):""),id?"PUT":"POST",data);await load();notice("Item saved.");});
action("deleteitem",async()=>{const id=$("itemid").value;if(id&&confirm("Delete this item and its associated data?")){await api("/items/"+encodeURIComponent(id),"DELETE");$("itemid").value="";await load();}});
action("addsource",async()=>{const id=$("itemid").value;if(!id)throw Error("Save or select an item first");await api("/items/"+encodeURIComponent(id)+"/sources","POST",{Name:$("sourcename").value,URL:$("sourceurl").value,Container:"mp4"});await sources();});
$("newlib").onsubmit=async e=>{e.preventDefault();try{await api("/libraries","POST",{name:$("libname").value,type:$("libtype").value});await load();}catch(e){notice(e.message,true);}};
$("newuser").onsubmit=async e=>{e.preventDefault();try{await api("/users","POST",{name:$("username").value,password:$("userpassword").value,is_admin:$("useradmin").checked});$("userpassword").value="";await load();}catch(e){notice(e.message,true);}};
function userpath(){const id=$("userid").value;if(!id)throw Error("Select a user first");return "/users/"+encodeURIComponent(id);}
action("savepolicy",async()=>{await api(userpath()+"/policy","PUT",JSON.parse($("policy").value));notice("Policy saved.");});action("resetpassword",async()=>{await api(userpath()+"/password","POST",{password:$("newpassword").value});$("newpassword").value="";notice("Password updated.");});action("deleteuser",async()=>{const p=userpath();if(confirm("Delete this user and their playback history?")){await api(p,"DELETE");$("userid").value="";await load();}});
for(const [id,dry]of [["dryrun",true],["runimport",false]])action(id,async()=>{if(!dry&&!confirm("Apply this import? Existing source/image/subtitle arrays will be replaced."))return;const data=JSON.parse($("importjson").value);data.dry_run=dry;const r=await api("/import","POST",data);$("importresult").textContent=JSON.stringify(r,null,2);notice(dry?"Dry run finished; no data written.":"Import finished. Review per-item errors.");});
